language: go
sudo: required
go:
  - "1.12"
services:
  - docker

go_import_path: github.ibm.com/istio-research/iter8-controller/

before_install:
  - ./test/scripts/tools.sh

script:
  - go test ./test/.
  - ./test/e2e/e2e.sh
