required = [
    "github.com/emicklei/go-restful",
    "github.com/onsi/ginkgo", # for test framework
    "github.com/onsi/gomega", # for test matchers
    "k8s.io/client-go/plugin/pkg/client/auth/gcp", # for development against gcp
    "k8s.io/code-generator/cmd/client-gen", # for go generate
    "k8s.io/code-generator/cmd/deepcopy-gen", # for go generate
    "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
    "sigs.k8s.io/controller-runtime/pkg/client/config",
    "sigs.k8s.io/controller-runtime/pkg/controller",
    "sigs.k8s.io/controller-runtime/pkg/handler",
    "sigs.k8s.io/controller-runtime/pkg/manager",
    "sigs.k8s.io/controller-runtime/pkg/runtime/signals",
    "sigs.k8s.io/controller-runtime/pkg/source",
    "sigs.k8s.io/testing_frameworks/integration", # for integration testing
	"k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1",
    ]

[prune]
  go-tests = true

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.16.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.16.3"

[[override]]
  name = "github.com/rogpeppe/go-internal"
  # HEAD as of 2019-01-09
  # Needed because release 1.0.0 does not contain a LICENSE file
  revision = "4bbc89b6501cca7dd6b5557d78d70c8d2c6e8b97"

[[constraint]]
  name="sigs.k8s.io/controller-runtime"
  version="=0.4.0"

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[constraint]]
  name = "istio.io/client-go"
  version = "1.4.0"
