apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: canaries.iter8.ibm.com
spec:
  group: iter8.ibm.com
  names:
    categories:
    - all
    - iter8
    kind: Canary
    plural: canaries
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            analysis:
              properties:
                analyticsService:
                  type: string
                metrics:
                  items:
                    properties:
                      confidence:
                        format: double
                        type: number
                      enableTrafficControl:
                        type: boolean
                      name:
                        type: string
                      sampleSize:
                        format: int64
                        type: integer
                      stopOnFailure:
                        type: boolean
                      type:
                        type: string
                      value:
                        format: double
                        type: number
                    required:
                    - name
                    - type
                    - value
                    type: object
                  type: array
              required:
              - analyticsService
              - metrics
              type: object
            targetService:
              type: object
            trafficControl:
              properties:
                interval:
                  type: string
                maxTrafficPercent:
                  format: double
                  type: number
                onSuccess:
                  type: string
                stepSize:
                  format: double
                  type: number
                strategy:
                  type: string
              required:
              - strategy
              type: object
          required:
          - targetService
          - trafficControl
          type: object
        status:
          properties:
            analysisState:
              type: object
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            lastIncrementTime:
              format: date-time
              type: string
            observedGeneration:
              format: int64
              type: integer
            progressing:
              type: boolean
          required:
          - lastIncrementTime
          - progressing
          - analysisState
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
