apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: reviews
  namespace: knative-bookinfo-iter8
spec:
  template:
    metadata:
      name: reviews-v5
    spec:
      containers:
      - image: iter8/reviews-v5:knative_0.1
        ports:
        - containerPort: 9080
          name: http1
        env:
        - name: VERSION
          value: v3
        - name: RATINGS_HOSTNAME
          value: ratings.knative-bookinfo-iter8.svc.cluster.local
        - name: RATINGS_SERVER_PORT
          value: "80"
  traffic:
  - revisionName: reviews-v2
    percent: 100
  - revisionName: reviews-v3
    percent: 0