apiVersion: iter8.tools/v1alpha1
kind: Experiment
metadata:
  name: reviews
  labels:
    app.kubernetes.io/name: reviews
spec:
  targetService:
    name: reviews
    apiVersion: v1 
    baseline: reviews-v2
    candidate: reviews-v3
  trafficControl:
    strategy: check_and_increment
    interval: 30s
    trafficStepSize: 20
    maxIterations: 5 #default value = 100
    maxTrafficPercentage: 99 #default value = 50
  analysis:
    analyticsService: "http://localhost:5555"
    successCriteria:
      - metricName: iter8_latency
        toleranceType: delta
        tolerance: 2
        sampleSize: 10
