apiVersion: v1
kind: Service
metadata:
  name: controller-manager-service
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: controller-manager
spec:
  selector:
    control-plane: controller-manager
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: {{ .Values.namespace }}
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      containers:
      - command:
        - /manager
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: manager
        env:
          - name: SERVICE_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: WEBHOOK_PORT
            value: value {{ .Values.service.port }}
        resources:
          limits:
            cpu: 100m
            memory: 75Mi
          requests:
            cpu: 100m
            memory: 50Mi
      terminationGracePeriodSeconds: 10
