apiVersion: iter8.tools/v1alpha2
kind: Experiment
metadata:
  name: reviews-v4-rollout
spec:
  service:
    name: reviews
    apiVersion: v1
    baseline: reviews-v3
    candidates: [ "reviews-v4" ]
  criteria:
    - metric: iter8_mean_latenecy
      threshold:
        type: absolute
        value: 200
  duration:
    interval: 30s
    maxIterations: 8
  trafficControl:
    maxIncrement: 20
  cleanup: true
  analyticsSerivceURL: http://iter8-analytics:8080
