apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-iex-https
  labels:
    app.kubernetes.io/name: stock-service-example
spec:
  hosts:
  - api.iextrading.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS