apiVersion: v1
kind: Service
metadata:
  labels:
    serving.knative.dev/release: devel
  name: prometheus-system-np-lb
  namespace: knative-monitoring
spec:
  type: LoadBalancer
  ports:
    - port: 9090
  selector:
    app: prometheus