apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: stock-canary-example
  labels:
    app.kubernetes.io/name: stock-canary-example
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: kimikowang/rest-api-go 
            env:
              - name: RESOURCE
                value: share
            readinessProbe:
              httpGet:
                path: /
              initialDelaySeconds: 0
              periodSeconds: 3
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: external-iex-https
  labels:
    app.kubernetes.io/name: stock-canary-example
spec:
  hosts:
  - api.iextrading.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
